source 'https://rubygems.org'

gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-theme-cayman'

group :jekyll_plugins do
  gem 'jekyll-relative-links'
  gem 'jekyll-optional-front-matter'
  gem 'jekyll-readme-index'
  gem 'jekyll-titles-from-headings'
end

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
